### ISSUE TITLE
Support For English 

### ISSUE THREAD

**Issue by omarsahl** [CrowniAPIs/libGDX-RTL-Language#1]
Does ArFont support LTR languages? If not, Is there any workaround to make it support both Arabic and English input?

**Comment by iibrahimbakr** [comment]
I updated `ArFont.class` to support LTR too.

**Comment by omarsahl** [comment]
Awesome!
I'll give it a spin right now.
Thank you.

**Comment by omarsahl** [comment]
Hey, 
I tried the updated library but AndroidStudio is having some issues with this line:
`Languages.inRange(Languages.ENGLISH, c);`
Thanks.

**Comment by iibrahimbakr** [comment]
I fixed it. Try now.
